# -*- coding: utf-8 -*-
"""Copy of Untitled84.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EIfTlcjJYV3ntJeUh0h-fglX2IP8i8rr
"""

with open("text.txt", "a") as f:
  f.write("Hello World")

#example of printing 1 to 10 (on seperate lines)
with open("text.txt", "a") as f:
  f.truncate(0)
  for i in range(1,11):
    f.write(str(i) + "\n")

with open("text.txt", "r") as f:
  data = f.readlines()
  newdata = []

  for element in data:
    newdata.append(int(element.rstrip()))

  newdata.sort(reverse = True)
  print(newdata)

# ["Mario","Daisy","Toad"]
names = ["Mario","Daisy","Toad"]
names.sort()
print(names)

# [["Mario",15],["Daisy",9],["Toad",2]]
# sort assending by score
names = [["Mario",15],["Daisy",9],["Toad",2]]

def sort_by_stars(val):
  return val[1]

names.sort(key=sort_by_stars)
print(names)

#[["Dom",16,420],["Ben",17, 542],["Mat",18,102]]
#sort by chess rating in decsending order
players = [["Dom",16,420],["Ben",17, 542],["Mat",18,102]]

def rating(e):
  return e[2]  # the rating

players.sort(key=rating, reverse = True)
print(players)

people = []
with open("data.txt","r") as f:
  data = f.readlines()
  
  for line in data:
    newline = line.strip()
    newline = newline.split(",")
    people.append(newline)
  
def sort_by_number(e):
  return int(e[1])
people.sort(key=sort_by_number, reverse=True)

with open("data_out.txt", "a") as f:
  f.truncate(0) #erase contents of file
  for p in people:
    line = p[0] + "," + str(p[1]) + "\n"
    f.write(line)