@startuml Animals
skinparam groupInheritance 2

Class Animal {
 -type
 -sound
 +speak()
}


Class Dog {
 -owener
 +walkies()
}

Class Pig {
 -nest
 +fly()
 +land()
}


Animal <|-- Dog
Animal <|-- Pig

@enduml